docs/requirements.txt

RTD installs a very old version of sphinx (<2.0), which is not compatible with `sphinx_autodoc_typehints`, see https://readthedocs.org/projects/audeer/builds/12143361/
So we force to use a newer version of sphinx.

DOC: require sphinx >= 3.0.0

---

docs/conf.py

The default i setting is to show a link to Gitlab in the right corner of the docs, this changes the link to Github.

DOC: show "Edit on Github" link

---

docs/api-audeer.rst

`run_workers_thread` is deprecated in favor of `run_tasks` and should be hidden from the docs.

DOC: hide deprecated run_workers_thread

---

audeer/core/io.py
audeer/core/utils.py
setup.cfg

Removes deprecated `run_worker_threads` from coverage as we will not add an extra test for it.

TST: don't cover deprecated run_worker_threads

---

audeer/core/io.py
tests/test_io.py

Closes #20 
This returns a list of members for `audeer.extract_archive()` and `audeer.extract_archives()`.
Now you can do:
```python
members = audeer.extract_archive()
```
What I don't like is that the returned objects depend on the underlying archive type.
E.g. when using a ZIP file we have 
```python
members[0].filename
```
whereas when it was a TAR.GZ archive we must use
```python
members[0].name
```
Which I find unfortunate.
Should we create our own archive object to abstract from the underlying objects, or just return filenames instead.
What was your use case for `members`?

Return members of archives in extract_archive(s)

---

audeer/__init__.py
audeer/core/utils.py
docs/api-audeer.rst
tests/test_utils.py

This adds a decorator to mark keyword arguments as deprecated.
Example:
```python
import audeer
@audeer.deprecated_keyword_argument(
deprecated_argument='foo',
alternative_argument='bar',
removal_version='1.0.0',
)   
def function_with_deprecated_keyword_argument(*, bar):
return bar 
```

Add audeer.deprecated_keyword_argument decorator

---

audeer/core/utils.py
tests/test_utils.py

Use `UserWarnings` instead of `DeprecationWarning` as the later ones are not shown in a default Python interpreter setting.

Switch to UserWarnings for deprecated decorators

---

audeer/__init__.py
audeer/core/io.py
docs/api-audeer.rst
tests/test_io.py

As a companion to `audeer.list_file_names()` this adds `audeer.list_dir_names()`.

Add audeer.list_dir_names()

---

audeer/__init__.py
audeer/core/utils.py
docs/api-audeer.rst
docs/conf.py
tests/test_utils.py

This adds a utility function that extracts a version number by the current git ref.
This will come handy for `audb.publish()` and can be used inside `docs/conf.py` to infer the current version for documentations.
It is not using a Python module to interact with git, but calls git directly which is easier and will not need another package.
If the command fails as `git` is not available or we are not inside a git repo, then `'<unknown>'` is returned as version.
Unfortunately, it is not that easy to write a test for this as it depends on the current stage of a git repo. So I repeated the code that should be executed in the test script.

Add audeer.version_from_git()

---

audeer/__init__.py
audeer/core/utils.py
docs/api-audeer.rst
tests/test_utils.py

As discussed in https://github.com/audeering/audeer/pull/27#issuecomment-769681087, this adds a function `git_tags()` which returns a list of all available tags.

Add audeer.git_tags()

---

audeer/__init__.py
audeer/core/utils.py
docs/api-audeer.rst
docs/conf.py
tests/test_utils.py

Closes #29 
It renames:
* `git_tags()` to `git_repo_tags()`
* `version_from_git()` to `git_repo_version()`

Rename git functions

---

audeer/__init__.py
audeer/core/utils.py
docs/api-audeer.rst
tests/test_utils.py

Adds decorator `utils.deprecated_default_value()`, which raises a warning that the default value of a keyword argument will change in a future version. The warning is not raised if the value is set explicitly.

Deprecated default value

---

audeer/__init__.py
audeer/core/utils.py
docs/api-audeer.rst
tests/test_utils.py

This adds `audeer.is_semantic_version()` to check that a given version number contains at least `X.Y.Z`, and that all those numbers are integers.

Add audeer.is_semantic_version()

---

audeer/core/utils.py
tests/test_utils.py

This now allows only for `X.Y.Z-bla` or `X.Y.Z+bla`, where `bla` can be anything and might containa `.` as well.
Added also more documentation to the doc string.

Be more strict on semantic versions

---

audeer/__init__.py
audeer/core/io.py
docs/api-audeer.rst
tests/test_io.py

Closes #19 by adding a function to create ZIP and TAR.GZ archives.

Add audeer.create_archive()

---

audeer/core/tqdm.py

As I find it hard to remember how to exactly use `audeer.progress_bar()` I added two examples to the docstring.
Before I didn't had an example as we can not easily execute it during building of the docs as the output is interactive.
But I decided now that it is more important to have an example as to make sure the code is executed.
The documentation now looks like this:

DOC: add example to audeer.progress_bar()

---

audeer/__init__.py
audeer/core/io.py
docs/api-audeer.rst
tests/test_io.py

This is the only path function that does not call `safe_path()` under the hood, but I think it makes more sense to not change the path here, but only the extension.

Add audeer.replace_file_extension()

---

audeer/__init__.py
audeer/core/io.py
docs/api-audeer.rst
tests/test_io.py

Add `audeer.download_url()` that uses `urllib.request` under the hood.
We had a similar implementation in https://github.com/audeering/audtorch/blob/21a745ff7fb6c16dd13823f1191e72971949abaa/audtorch/datasets/utils.py#L66-L107, and I think it might be useful to make this available in general.

Add audeer.download_url()

---

audeer/__init__.py
audeer/core/io.py
docs/api-audeer.rst
tests/conftest.py
tests/test_io.py

As I don't like to import `shutil` everytime I need to delete a directory and also first check if the directory exists, I decided to add `audeer.rmdir()`.

Add audeer.rmdir()

---

audeer/core/io.py

We already had a verbose argument to show a progress bar in `extract_archive()`. This adds one to `create_archive()`. It also simplifies the code where we create the progress bar in `extract_archive()`.

Add verbose flag to create_archive()

---

audeer/__init__.py
audeer/core/io.py
docs/api-audeer.rst
tests/conftest.py
tests/test_io.py

This adds `audeer.touch()` to create an empty file.
I think it is easier to remember and looks better as `open(path, 'a').close()`
I also use `audeer.touch()` now in the example for `audeer.list_file_names()`

Add audeer.touch()

---

audeer/__init__.py
audeer/core/io.py
docs/api-audeer.rst
tests/conftest.py
tests/test_io.py

As proposed in https://github.com/audeering/audb/pull/175#discussion_r813996803 this adds `audeer.move_file()`.

Add audeer.move_file()

---

.github/workflows/test.yml
audeer/core/io.py
tests/test_io.py

Closes #46.
Add a test for macOS and restrict Windows and MacOS tests to Python 3.8.
I also disabled the docstring test for `audeer.common_directory()` under MacOS as it puts a `/System/Volumes/Data` in front of the path in the Github runner.

CI: add test for macOS

---

audeer/__init__.py
audeer/core/utils.py
audeer/core/version.py
docs/api-audeer.rst
tests/test_version.py

Closes #55
This adds `audeer.LooseVersion` and `audeer.StrictVersion` copying the implementation of `distutils.version.LooseVersion` from https://github.com/python/cpython/blob/20a1c8ee4bcb1c421b7cca1f3f5d6ad7ce30a9c9/Lib/distutils/version.py

Add audeer.LooseVersion() and audeer.StrictVersion()

---

audeer/core/io.py
tests/test_io.py

Closes #18.
This expands `audeer.safe_path()` by adding an optional `*paths` argument, which allows to provide parts of a path, which are then first joined by `os.path.join()`.

Possibility to join paths in audeer.safe_path()

---

audeer/__init__.py
audeer/core/io.py
audeer/core/path.py
docs/api-audeer.rst
tests/test_io.py
tests/test_path.py

As suggested in https://github.com/audeering/audeer/pull/58#issuecomment-1056896331 this adds `audeer.path()`.
It also extends the docstring compared to what we had before in `audeer.safe_path()`.
I added a warning to `audeer.safe_path()` in the documentation:

Add audeer.path()

---

audeer/core/io.py
tests/conftest.py
tests/test_io.py

Closes #66 
To be backward compatible defaults to `False` for `audeer.list_file_names()` and to `True` for `audeer.list_dir_names()`.

Add argument to include hidden files

---

tests/requirements.txt

Newer version of flake8 do not work with the `pytest-flake8` plugin and will most likely not be fixed, see https://github.com/tholo/pytest-flake8/issues/87

TST: depend on flake8<5.0.0

---

audeer/core/utils.py
tests/test_utils.py

Closes #69 
This adds the keyword argument `remove_from_kwargs` to `audeer.deprecated_keyword_argument()` with default setting of `True`, which was the behavior before. If you set it to `False` it will not remove the deprecated keyword argument from `kwargs`.

Add remove_from_kwargs argument to deprecated_keyword_argument()

---

audeer/core/io.py
tests/test_io.py

As mentioned in #76 `audeer.list_dir_names()` did not have documented or tested the cases where it raises an error.
This is changed here.

DOC: add raises section for list_dir_names()

---

audeer/core/io.py
tests/test_io.py

Closes #75 
The argument for the new extension is named `new_extension`, but I decided to use the name `ext` and not `extension` as we also have this argument in `audeer.basename_wo_ext()`.

Add ext argument to replace_file_extension()

---

.github/workflows/test.yml

Defines `main` as new default branch name to decide when to run tests.

TST: adjust default branch to main

---

.github/workflows/flake8.yml
.pre-commit-config.yaml
CONTRIBUTING.rst
setup.cfg
tests/requirements.txt
tests/test_io.py

This uses [pre-commit](https://pre-commit.com) instead of `pytest` to execute the `flake8` tests.
It also fixes a few flake8 issues and adds a coding convention section to CONTRIBUTING.

TST: use pre-commit for flake8 checks

---

tests/requirements.txt

Remove unneeded `pytest-flake8` from `tests/requirements.txt`

TST: remove pytest-flake8 from requirements

---

audeer/core/io.py
tests/test_io.py

Closes #89 #87 
Fixes #89 and #87 ~~and raises an error if `path` does not end on `ext`~~. For consistency with `ext`, `new_extension` may now also start with a dot.

Fix audeer.replace_file_extension() for empty extensions

---

audeer/core/utils.py
tests/test_utils.py

Closes #88 
In `audb` were we used for short IDs for the first time we started to use the last 8 digits, which we also do here. The 8 digits would have been a better choice as the following example shows:
```python
for short in False, True:
for idx in range(2):
uid = audeer.uid(short=short)
print(uid)
```
```
db88e120-9e2f-11ed-a57a-80fa5b66caff
db88e121-9e2f-11ed-a57a-80fa5b66caff
5b66caff
5b66caff
```
This is also the reason I had to simplify the test for short IDs.

Add support for short ID

---

audeer/core/io.py
tests/test_io.py

Closing #76 
This documents when `audeer.list_file_names()` raises an error and also adds the corresponding tests for it.

DOC: add raises section to list_file_names()

---

audeer/core/version.py

Adds a missing raises section to the docstring of `audeer.StrictVersion`

DOC: add raises section to audeer.StrictVersion

---

audeer/__init__.py
audeer/core/io.py
docs/api-src/audeer.rst
tests/test_io.py

Implements functions to calculate MD5 checksum for a file or a whole folder:
The function can then be used by `audb` and `audbackend`, which currently implement their own functions.

Add audeer.md5()

---

.coveragerc.Linux
.coveragerc.Windows
.coveragerc.macOS
.github/workflows/test.yml
audeer/core/io.py

Closes #107 
Exclude Windows only code from coverage to be able to reach full coverage when just running
```bash
$ python -m pytest
```

TST: exclude Windows only code from coverage

---

CHANGELOG.rst

Closes #109 
This adds a missing changelog entry for the 1.20.0 release, mentioning that return values of `audeer.extract_archive()` and `audeer.extract_archives()` have changed to normalized paths.
/cc @Bahaabrougui

DOC: add missing 1.20.0 changelog entry

---

.github/workflows/publish.yml

We updated to use pyproject.toml in https://github.com/audeering/audeer/pull/114, but forgot to update the publish Action accordingly.

CI: update publish Action to new pyproject.toml

---

.github/workflows/doc.yml
.github/workflows/test.yml

Use a separate GitHub Action stage for testing building the documentation and remove it from the other test definitions.

CI: use separate Action for testing docs

---

audeer/__init__.py

`pkg_resources` is deprecated and since Python 3.8 we can use `importlib.metadata` to get the version of a package.

Use importlib.metadata instead of pkg_resources

---

audeer/core/io.py
tests/test_io.py

Similar to https://github.com/audeering/audeer/pull/126 this adds support for `*paths` to `audeer.touch()`.
This allows a syntax like `audeer.touch('folder', 'file.txt')`.
We have a few more functions that have `path` as input, but we cannot add support for `*paths` to all of them, e.g. `move_file()` requires `src_path` and `dst_path`. Besides `audeer.touch()`, we might consider to add it to `audeer.list_file_names()` and `audeer.list_dir_names()`, but I'm not completely convinced ;)

Support *paths in touch()

---

audeer/core/conftest.py
audeer/core/path.py
tests/test_path.py

Closes #131 
This adds the `follow_symlink` argument to `audeer.path()` (~~but not to `audeer.safe_path()`~~), which can be used to speed up it's processing when it is not important to convert symbolic links to the actual file paths.
Execution time when running on 1,000,000 files.
| `follow_symlink=True` | `follow_symlink=False` |
| --- | --- |
| 12.03 s | 2.22 s |
<details><summary>Benchmark code</summary>
```python
import tempfile
import time
import audeer
repetitions = 1000000
with tempfile.TemporaryDirectory() as tmpdir:
files = [ 
audeer.touch(audeer.path(tmpdir, 'benchmark-{n}.txt'))
for n in range(repetitions)
]   
for follow_symlink in [True, False]:
t = time.time()
for file in files:
audeer.path(file, follow_symlink=follow_symlink)
print(f'{time.time() - t:.2f} s')
```
</details>

Add follow_symlink argument to audeer.path()

---

audeer/core/path.py

Relates to https://github.com/audeering/audeer/issues/136
Changes the default of `follow_symlink` in `audeer.path()` to `False`.
Also fixes handing the `follow_symlink` settings to `audeer.path()` in `audeer.safe_path()`.

follow_symlink=False as default in path()

---

tests/test_io.py

This adds tests for the handling of symbolic links to `audeer.md5()` and `audeer.list_file_names()` (as this is used inside `audeer.md5()`). 
It turns out that all those newly added tests do also pass when we change the default of `follow_symlink` to `True` in `audeer.path()` as we did already not convert symlinks in `audeer.list_file_names()`, which is used inside `audeer.md5()` to list file names in a folder. This means we do not need to adapt `audeer.md5()` at all for https://github.com/audeering/audeer/pull/140.

TST: symlink in md5() and list_file_names()

---

audeer/core/io.py
tests/test_io.py

This adds the `follow_symlink` argument to `audeer.rmdir()`, but sets it to `True` as default as this is avoids breaking changes and seems to be a meaningful behavior.
I decided against silently setting it to `True` internally as we still use `audeer.rmdir()` in loops that can get a speed up by ensuring that we don't have a symbolic link before we call `audeer.rmdir()`, e.g. https://github.com/audeering/audb/blob/12ad8520e45c11f152c5c96b11f221e3a1fb40f2/audb/core/load_to.py#L303-L329
I also added tests and included a new error under Raises section in the docstring that can happen with `follow_symlink=False`.

Add follow_symlink argument to rmdir()

---

CHANGELOG.rst

I decided for a new major release of `audeer` as we have breaking changes for a lot of its functions. Fortunately, the consequences shouldn't be too bad.
I checked our main three packages and created pull requests with the needed adaptations:
* [audformat](https://github.com/audeering/audformat/pull/411)
* [audb](https://github.com/audeering/audb/pull/348)
* [audinterface](https://github.com/audeering/audinterface/pull/153), no changes needed

Release 2.0.0

---

.github/workflows/doc.yml
.github/workflows/linter.yml
.github/workflows/publish.yml
.github/workflows/test.yml

Update CI actions to their latest versions, and switch publish and doc CI job to use Python 3.10 instead of Python 3.8.

CI: update Actions, Python 3.10 as default

---

tests/test_io.py

Under Linux and MacOS the error message when trying to delete a symlink with `audeer.rmdir(link, follow_symlink=False)` is broken for Python==3.12.4 (and maybe earlier versions as well.
We simply skip the comparison for now.

TST: fix symlink removal error message

---

audeer/core/tqdm.py
tests/test_tqdm.py

This adds `maximum_refresh_time` which allows to ensure that a progress bar is refreshed at least every `maximum_refresh_time` seconds.
This is of interest when the time between the single steps of the progress bar iteration take very long, and a user might start to wonder if the process is stalled or still running.
The refreshing is achieved by using another thread as proposed in https://github.com/tqdm/tqdm/issues/861#issuecomment-2197893883. To not change and possible break any existing code, the default value of `maximum_refresh_time` is `None` which will not force refreshing the progress bar. I would propose we set this value then to an actual value in applications where it is relevant, e.g. `audb`.
For a local example run:
```python
import time
import audeer
for _ in …
```

Add maximum_refresh_time to progress_bar()

---

audeer/core/utils.py

This fixes the docstring of `audeer.run_tasks()` by changing its return type from sequence to list, and adds missing documentation of its return value.

DOC: fix return value of run_tasks()

---

audeer/core/utils.py

This is a follow up of https://github.com/audeering/audeer/pull/147, and adds the new `maximum_refresh_time` of `audeer.progress_bar()` to `audeer.run_tasks()` as well.

Add maximum_refresh_time to run_tasks()

---

audeer/__init__.py
audeer/core/utils.py
docs/api-src/audeer.rst
tests/test_utils.py

It might be that a user wants to get unique values of a sequence, in the order they are appearing in that sequence.

Add audeer.unique()

---

audeer/core/tqdm.py

Closes https://github.com/audeering/audb/issues/442
This makes the estimation of the remaining time in the progress bar less eratic.
For a single thread it changed the behavior from
to
And when using 4 threads it changes the behavior from
to

Use smoothing=0 in audeer.progress_bar()

---

audeer/__init__.py
audeer/core/io.py
docs/api-src/audeer.rst
tests/test_io.py

Very often, I add the following to the top of a script:
```python
CURRENT_DIR = os.path.dirname(os.path.realpath(__file__))
```
and I need to google it every time.
To make it easier to remember, this pull request proposes to add `audeer.script_dir()` which can be used instead.
When called in an interactive session, it returns the directory the user is located in.

Add audeer.script_dir()

---

pyproject.toml

Updates to the new official syntax for license in `pyproject.toml`.

Fix license syntax in pyproject.toml
