audeering/audeer

docs/installation.rst

Incorporate creation and activation of virtual environment into install instructions.

DOC: add virtual environment to installation

---

docs/conf.py
docs/installation.rst
docs/requirements.txt

Adds the copy-button Sphinx extension, dealing with Python and bash prompts.

Use copy button

---

README.rst
docs/usage.rst

Would be nice to have an usage example inside the README.

DOC: add estimating pi example to usage

---

.github/workflows/publish.yml

Test deployment of documentation as Github pages

DOC: publish documentation as Github pages

---

README.rst

Add a code coverage badge to the readme

DOC: add code coverage badge to readme

---

CONTRIBUTING.rst

Simplify instructions in CONTRIBUTING

DOC: adjust release instructions to Github

---

.github/workflows/test.yml
audeer/core/io.py
tests/test_io.py

Add test for Windows and update the package to make it Windows compatible.

TST: add Windows tests

---

audeer/__init__.py
audeer/core/utils.py
docs/api-audeer.rst
tests/test_utils.py

Adds a function `is_uid` that takes as input a string and returns `True` if the string represents a unique identifier.

Add function is_uid

---

tests/test_io.py

Add tests for:
* empty input file name
* file extension including uppercase letters

TST: expand tests for audeer.file_extension()

---

audeer/core/utils.py

Just some clean up to make sure `import xyz` are listed in sorted order and to fix some other small issues.

Correctly sort imports

---

audeer/core/io.py

Closes #37 
Just realized I commited changes to both functions and not only to `audeer.list_dir_names()`.
So I changed the title as it should be fine to add both in a single commit.

Add basename argument to audeer.list_*_names()

---

audeer/core/utils.py

Change default to num_workers=1 in run_tasks()

---

docs/requirements.txt

Switch to our new audEERING theme colors.

DOC: use new sphinx-audeering-theme

---

audeer/core/io.py
tests/conftest.py
tests/test_io.py

list_dir_names(): add recursive argument

---

CHANGELOG.rst

Release 1.18.0

---

CHANGELOG.rst

Release 1.19.0

---

.coveragerc.Linux
.coveragerc.Windows
.coveragerc.macOS
.github/workflows/test.yml
audeer/core/io.py
audeer/core/utils.py
tests/test_io.py

Closes #101 #102 
* Check if files are below root
* Check that files exist
* Check that archive is not a folder
* Check that root / destination is a folder
* Extend raises sections
* Include all files if files is None

Fix archive errors and support files is None

---

audeer/core/io.py

DOC: add examples to archive functions

---

CHANGELOG.rst

Release 1.20.0

---

CHANGELOG.rst

Release 1.20.1

---

.github/workflows/doc.yml
CHANGELOG.rst

Enables link checking when testing building the documentation.

CI: enable link check and fix links

---

CHANGELOG.rst

Release 1.20.2

---

CHANGELOG.rst

Release 1.21.0

---

CHANGELOG.rst

Release 2.1.1

---

CHANGELOG.rst

For reference, `audeer.script_dir()` was added in https://github.com/audeering/audeer/pull/155

Release 2.2.0
